const phi = (1 + Math.sqrt(5)) / 2;
const fib = (n) => {
    return  Math.round((Math.pow(phi, n) - Math.pow(-phi,-n)) / Math.sqrt(5));
};

console.log(fib(1));
console.log(fib(2));
console.log(fib(3));
console.log(fib(4));
console.log(fib(5));
console.log(fib(6));
console.log(fib(7));
console.log(fib(8));
console.log(fib(9));
console.log(fib(10));
console.log(fib(11));
console.log(fib(12));
console.log(fib(13));
console.log(fib(14));
console.log(fib(15));
console.log(fib(16));
console.log(fib(17));
console.log(fib(18));
console.log(fib(19));
console.log(fib(20));
console.log(fib(21));
console.log(fib(22));
console.log(fib(23));
console.log("Num:24:",fib(24));
console.log(fib(25));
console.log(fib(26));
console.log(fib(27));
console.log("Num:28",fib(28));
console.log("Num:29",fib(29));
console.log("Num:30",fib(30));
